services:
  - name: tb-futures
    type: web
    runtime: docker
    plan: free
    region: ohio
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
